language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
- cargo clean
- cargo build
- cargo test

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
    tar xzf master.tar.gz
    cd kcov-master
    mkdir build
    cd build
    cmake ..
    make
    sudo make install && cd ../.. &&
    kcov --coveralls-id=$repo_token --exclude-pattern=/.cargo,/usr/lib --exclude-region='#[cfg(test)]:#[cfg(testkcovstopmarker)]' --verify target/cov target/debug/keygraph_rs-*;
  fi
